### ISSUE TITLE
Config json doesn't seem to work

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [alkyaly/Somnia-Fabric#2]
**MC** 1.17.1
**Somnia** 1.1.1

I've changed "displayFatigue" to "TOP_RIGHT", "minimumFatigueToSleep" to 1.0, "baseMultiplier" to 3, "sleepWithArmor" to true, and "timings" to its vanilla values to allow sleeping only at night. But nothing changed in game.

**Comment by Footage2-Amply-Pounce** [comment]
> 
> 
> Could you send the latest.log? It should be in `game-folder/logs/`

[latest.log](https://github.com/alkyaly/Somnia-Fabric/files/7269010/latest.log)

**Comment by alkyaly** [comment]
```
[19:11:52] [Render thread/ERROR]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 26 path $.fatigue.Accepted
[19:11:52] [Render thread/INFO]: Encountered an error while reading somnia config, falling back to default values.
[19:11:52] [Render thread/INFO]: If this problem persists, delete the config file somnia.json5 and try again.
```
Send your config file, something probably went wrong or it was serialized incorrectly

**Comment by Footage2-Amply-Pounce** [comment]
> 
> 
> ```
> [19:11:52] [Render thread/ERROR]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 26 path $.fatigue.Accepted
> [19:11:52] [Render thread/INFO]: Encountered an error while reading somnia config, falling back to default values.
> [19:11:52] [Render thread/INFO]: If this problem persists, delete the config file somnia.json5 and try again.
> ```
> 
> Send your config file, something probably went wrong or it was serialized incorrectly

I had to add .txt so that github would let me upload it [somnia.json5.txt](https://github.com/alkyaly/Somnia-Fabric/files/7269067/somnia.json5.txt)

**Comment by alkyaly** [comment]
Oh...
I forgot I was bundling my own version of omega config without changing the id, that is really my bad
Will fix soon
